### ISSUE TITLE
Reactor 2 Display

### ISSUE THREAD

**Issue by PSZoneUK** [Skyamoeba/FTBUKLW#4]
Error in typing for colour for Reactor B Temp on external monitor.
Error Line shown below:

function ReactorBTemp()

if RBCommP.getCasingTemperature()>=650 then
        if ReactorB[9] == 1 then
        mon2.setCursorPos(3,7)
-->   RTRAMONCOL(TXTCOL[11])
        end

**Comment by UKLoneWolf** [comment]
Its a quick to fix so I will add a few more bits and bobs as I sort that out.
Might be a build update not a full update as its not a program breaking bug so manual update might be required but I will decide this when I finish the things I want to do.

**Comment by UKLoneWolf** [comment]
Closed and cured issues above in 
Ver: 0.3..9
Build: 01.15.0.5
